version: '3.8'

services:
  app:
    image: mtichy22/symfony-app:latest
    volumes:
      - .:/var/www
    ports:
      - '80:80'
    depends_on:
      - db

  db:
    image: mariadb:10.4.2
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: